name: PHP CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.2', '8.3']

    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
          coverage: xdebug

      - name: Install
        run: make install

      - name: Run linter
        run: make lint analyse

      - run: make test

      # - name: Run test & publish code coverage
      #   uses: paambaati/codeclimate-action@v9.0.0
      #   env:
      #     CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      #   with:
      #     coverageCommand: make test-coverage
      #     coverageLocations: ${{github.workplace}}/build/logs/clover.xml:clover
      #     debug: true
